-- Create databases
CREATE DATABASE ${MLFLOW_METADATA_DB_NAME};
CREATE DATABASE ${MLFLOW_AUTH_DB_NAME};
CREATE DATABASE ${LUIGI_DB_NAME};
CREATE DATABASE ${APP_DB_NAME};

-- Create users for each database
CREATE USER ${MLFLOW_METADATA_DB_USER} WITH PASSWORD ${MLFLOW_METADATA_DB_PASSWORD};
CREATE USER ${MLFLOW_AUTH_DB_USER} WITH PASSWORD ${MLFLOW_AUTH_DB_PASSWORD};
CREATE USER ${LUIGI_DB_USER} WITH PASSWORD ${LUIGI_DB_PASSWORD};
CREATE USER ${APP_DB_USER} WITH PASSWORD ${APP_DB_PASSWORD};

-- Grant privileges
GRANT ALL PRIVILEGES ON DATABASE ${MLFLOW_METADATA_DB_USER} TO ${MLFLOW_METADATA_DB_USER};
GRANT ALL PRIVILEGES ON DATABASE ${MLFLOW_AUTH_DB_USER} TO ${MLFLOW_AUTH_DB_USER};
GRANT ALL PRIVILEGES ON DATABASE ${LUIGI_DB_USER} TO ${LUIGI_DB_USER};
GRANT ALL PRIVILEGES ON DATABASE ${APP_DB_USER} TO ${APP_DB_USER};
