-- Create databases
CREATE DATABASE ${MLFLOW_METADATA_DB_NAME};
CREATE DATABASE ${MLFLOW_AUTH_DB_NAME};
CREATE DATABASE ${LUIGI_DB_NAME};
CREATE DATABASE ${APP_DB_NAME};

-- Create users for each database
CREATE USER ${MLFLOW_METADATA_DB_USER} WITH PASSWORD '${MLFLOW_METADATA_DB_PASSWORD}';
CREATE USER ${MLFLOW_AUTH_DB_USER} WITH PASSWORD '${MLFLOW_AUTH_DB_PASSWORD}';
CREATE USER ${LUIGI_DB_USER} WITH PASSWORD '${LUIGI_DB_PASSWORD}';
CREATE USER ${APP_DB_USER} WITH PASSWORD '${APP_DB_PASSWORD}';

-- Grant privileges
GRANT ALL PRIVILEGES ON DATABASE ${MLFLOW_METADATA_DB_NAME} TO ${MLFLOW_METADATA_DB_USER};
GRANT ALL PRIVILEGES ON DATABASE ${MLFLOW_AUTH_DB_NAME} TO ${MLFLOW_AUTH_DB_USER};
GRANT ALL PRIVILEGES ON DATABASE ${LUIGI_DB_NAME} TO ${LUIGI_DB_USER};
GRANT ALL PRIVILEGES ON DATABASE ${APP_DB_NAME} TO ${APP_DB_USER};

-- Grant schema privileges for each database
-- For MLFLOW_METADATA_DB
\connect ${MLFLOW_METADATA_DB_NAME}
ALTER DATABASE ${MLFLOW_METADATA_DB_NAME} OWNER TO ${MLFLOW_METADATA_DB_USER};
GRANT ALL PRIVILEGES ON SCHEMA public TO ${MLFLOW_METADATA_DB_USER};
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ${MLFLOW_METADATA_DB_USER};
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO ${MLFLOW_METADATA_DB_USER};
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO ${MLFLOW_METADATA_DB_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO ${MLFLOW_METADATA_DB_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO ${MLFLOW_METADATA_DB_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO ${MLFLOW_METADATA_DB_USER};

-- For MLFLOW_AUTH_DB
\connect ${MLFLOW_AUTH_DB_NAME}
ALTER DATABASE ${MLFLOW_AUTH_DB_NAME} OWNER TO ${MLFLOW_AUTH_DB_USER};
GRANT ALL PRIVILEGES ON SCHEMA public TO ${MLFLOW_AUTH_DB_USER};
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ${MLFLOW_AUTH_DB_USER};
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO ${MLFLOW_AUTH_DB_USER};
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO ${MLFLOW_AUTH_DB_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO ${MLFLOW_AUTH_DB_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO ${MLFLOW_AUTH_DB_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO ${MLFLOW_AUTH_DB_USER};

-- For LUIGI_DB
\connect ${LUIGI_DB_NAME}
ALTER DATABASE ${LUIGI_DB_NAME} OWNER TO ${LUIGI_DB_USER};
GRANT ALL PRIVILEGES ON SCHEMA public TO ${LUIGI_DB_USER};
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ${LUIGI_DB_USER};
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO ${LUIGI_DB_USER};
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO ${LUIGI_DB_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO ${LUIGI_DB_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO ${LUIGI_DB_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO ${LUIGI_DB_USER};

-- For APP_DB
\connect ${APP_DB_NAME}
ALTER DATABASE ${APP_DB_NAME} OWNER TO ${APP_DB_USER};
GRANT ALL PRIVILEGES ON SCHEMA public TO ${APP_DB_USER};
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ${APP_DB_USER};
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO ${APP_DB_USER};
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO ${APP_DB_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO ${APP_DB_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO ${APP_DB_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO ${APP_DB_USER};
